name: '"Template Substitution" for GitHub Actions'
description: Hydrate template files from the environment
branding:
  icon: copy
  color: blue
inputs:
  from:
    description: Path on local disk where the target `.tpl.*` can be found
    required: true
  to:
    description: Specify the target output path, including file name
    required: true
outputs:
  location:
    description: Essentially provides the `to` input as an output, useful in cases where `to` may have been dynamically generated.
runs:
  using: node16
  main: dist/index.js
