name: '"Template Substitution" for GitHub Actions'
description: Hydrate template files from the environment
branding:
  icon: copy
  color: blue
inputs:
  from:
    description: Path on local disk where the target `.tpl.*` can be found
    required: true
  to:
    description: Specify the target output path, including file name
    required: true
outputs:
  content:
    description: Provides all content resultant from template substitution
  to:
    description: Provides the path at which the hydrated file is located. Useful if `to` input was not provided
runs:
  using: node16
  main: dist/index.js
