name: '"Template Substitution" for GitHub Actions'
description: Hydrate template files from the environment
branding:
  icon: copy
  color: blue
inputs:
  from:
    description: Path on local disk where the target `.tpl.*` can be found
    required: true
  to:
    description: Optionally specify the target output path. If none is provided, we'll use the `to` path with `.tpl` removed
    required: false
outputs:
  content:
    description: Provides all content resultant from template substitution
  to:
    description: Provides the path at which the hydrated file is located. Useful if `to` input was not provided
runs:
  using: node16
  main: dist/index.js
